name: Validate and build

on:
  pull_request:
    paths:
      - 'python/**'
  push:
    branches: [main]
    paths:
      - 'python/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci-sdk-python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13", "3.14"]

    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/uv
          key: sdk-python-${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            sdk-python-${{ runner.os }}-python-${{ matrix.python-version }}-

      - name: Setup
        run: make .venv


      - name: Run the lint+tests
        if: |
          !(github.event_name == 'push' && github.ref_name == 'main')
        run: make

      - name: Build dist
        if: |
          !(github.event_name == 'push' && github.ref_name == 'main')
        run: make dist

  trigger-integration-tests:
    needs: ci-sdk-python
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Trigger downstream workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          repository: ${{ secrets.DOWNSTREAM_REPO }}
          event-type: python-sdk-integration-tests
          client-payload: |
            {
              "ref": "${{ github.event.pull_request.head.sha }}",
              "branch": "${{ github.event.pull_request.head.ref }}",
              "pr_number": "${{ github.event.pull_request.number }}"
            }
